### ISSUE TITLE
翻訳版

### ISSUE THREAD

**Issue by nzws** [Resicaxo/Invisible_Maze#3]
があるといろいろなユーザー取り込めそう

**追記: そもそもアプリ自体は英語しかなかった**

**Comment by nzws** [comment]
参考: http://lhsp.s206.xrea.com/hsp_system.html#10

**Comment by Resicaxo** [comment]
プログラムのメモを翻訳するのか…死にそう。
とりあえずREADMEだけでも翻訳してみる。

**Comment by nzws** [comment]
ちょい雑イングリッシュでよければわしやろうか？
